/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_audiotest_module_OpusWrapper */

#ifndef _Included_com_example_audiotest_module_OpusWrapper
#define _Included_com_example_audiotest_module_OpusWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_audiotest_module_OpusWrapper_OPUS_TYPE_ENCODER
#define com_example_audiotest_module_OpusWrapper_OPUS_TYPE_ENCODER 1L
#undef com_example_audiotest_module_OpusWrapper_OPUS_TYPE_DECODER
#define com_example_audiotest_module_OpusWrapper_OPUS_TYPE_DECODER 2L
#undef com_example_audiotest_module_OpusWrapper_OPUS_APPLICATION_VOIP
#define com_example_audiotest_module_OpusWrapper_OPUS_APPLICATION_VOIP 1L
#undef com_example_audiotest_module_OpusWrapper_OPUS_APPLICATION_AUDIO
#define com_example_audiotest_module_OpusWrapper_OPUS_APPLICATION_AUDIO 2L
#undef com_example_audiotest_module_OpusWrapper_OPUS_APPLICATION_RESTRICTED_LOWDELAY
#define com_example_audiotest_module_OpusWrapper_OPUS_APPLICATION_RESTRICTED_LOWDELAY 3L
#undef com_example_audiotest_module_OpusWrapper_OPUS_SIGNAL_TYPE_AUTO
#define com_example_audiotest_module_OpusWrapper_OPUS_SIGNAL_TYPE_AUTO 4L
#undef com_example_audiotest_module_OpusWrapper_OPUS_SIGNAL_TYPE_MUSIC
#define com_example_audiotest_module_OpusWrapper_OPUS_SIGNAL_TYPE_MUSIC 5L
#undef com_example_audiotest_module_OpusWrapper_OPUS_SIGNAL_TYPE_VOICE
#define com_example_audiotest_module_OpusWrapper_OPUS_SIGNAL_TYPE_VOICE 6L
#undef com_example_audiotest_module_OpusWrapper_OPUS_BANDWIDTH_NARROWBAND
#define com_example_audiotest_module_OpusWrapper_OPUS_BANDWIDTH_NARROWBAND 7L
#undef com_example_audiotest_module_OpusWrapper_OPUS_BANDWIDTH_MEDIUMBAND
#define com_example_audiotest_module_OpusWrapper_OPUS_BANDWIDTH_MEDIUMBAND 8L
#undef com_example_audiotest_module_OpusWrapper_OPUS_BANDWIDTH_WIDEBAND
#define com_example_audiotest_module_OpusWrapper_OPUS_BANDWIDTH_WIDEBAND 9L
#undef com_example_audiotest_module_OpusWrapper_OPUS_BANDWIDTH_SUPERWIDEBAND
#define com_example_audiotest_module_OpusWrapper_OPUS_BANDWIDTH_SUPERWIDEBAND 10L
#undef com_example_audiotest_module_OpusWrapper_OPUS_BANDWIDTH_FULLBAND
#define com_example_audiotest_module_OpusWrapper_OPUS_BANDWIDTH_FULLBAND 11L
/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusInit
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusInit
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusDestroy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusDestroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusEncode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusEncode
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusDecode
 * Signature: ([BI[SIZ)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusDecode
  (JNIEnv *, jobject, jbyteArray, jint, jshortArray, jint, jboolean);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusSetComplexity
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusSetComplexity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusSetSignalType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusSetSignalType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusSetBandwidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusSetBandwidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusResetSampleRate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusResetSampleRate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusAdjustBitrate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusAdjustBitrate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusSetGainValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusSetGainValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusGetPitchValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusGetPitchValue
  (JNIEnv *, jobject);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusSetLSBDepth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusSetLSBDepth
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusSetDTX
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusSetDTX
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusInBandFEC
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusInBandFEC
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_audiotest_module_OpusWrapper
 * Method:    opusPacketLostPerc
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_OpusWrapper_opusPacketLostPerc
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
