/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_audiotest_module_VADWrapper */

#ifndef _Included_com_example_audiotest_module_VADWrapper
#define _Included_com_example_audiotest_module_VADWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_audiotest_module_VADWrapper_VAD_SEND_SIDE
#define com_example_audiotest_module_VADWrapper_VAD_SEND_SIDE 1L
#undef com_example_audiotest_module_VADWrapper_VAD_RECV_SIZE
#define com_example_audiotest_module_VADWrapper_VAD_RECV_SIZE 2L
/*
 * Class:     com_example_audiotest_module_VADWrapper
 * Method:    vadInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_VADWrapper_vadInit
  (JNIEnv *, jobject);

/*
 * Class:     com_example_audiotest_module_VADWrapper
 * Method:    vadDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_audiotest_module_VADWrapper_vadDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_example_audiotest_module_VADWrapper
 * Method:    vadProcess
 * Signature: (I[SII)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_VADWrapper_vadProcess
  (JNIEnv *, jobject, jint, jshortArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
