/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_audiotest_module_AGCWrapper */

#ifndef _Included_com_example_audiotest_module_AGCWrapper
#define _Included_com_example_audiotest_module_AGCWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_audiotest_module_AGCWrapper_AGC_MODE_UNCHANGED
#define com_example_audiotest_module_AGCWrapper_AGC_MODE_UNCHANGED 1L
#undef com_example_audiotest_module_AGCWrapper_AGC_MODE_ADAPTIVE_ANALOG
#define com_example_audiotest_module_AGCWrapper_AGC_MODE_ADAPTIVE_ANALOG 2L
#undef com_example_audiotest_module_AGCWrapper_AGC_MODE_ADAPTIVE_DIGITAL
#define com_example_audiotest_module_AGCWrapper_AGC_MODE_ADAPTIVE_DIGITAL 3L
#undef com_example_audiotest_module_AGCWrapper_AGC_MODE_FIXED_DIGITAL
#define com_example_audiotest_module_AGCWrapper_AGC_MODE_FIXED_DIGITAL 4L
/*
 * Class:     com_example_audiotest_module_AGCWrapper
 * Method:    agcInit
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_AGCWrapper_agcInit
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_example_audiotest_module_AGCWrapper
 * Method:    agcDestroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_AGCWrapper_agcDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_example_audiotest_module_AGCWrapper
 * Method:    agcProcess
 * Signature: ([S[S[S[SII[II)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_AGCWrapper_agcProcess
  (JNIEnv *, jobject, jshortArray, jshortArray, jshortArray, jshortArray, jint, jint, jintArray, jint);

/*
 * Class:     com_example_audiotest_module_AGCWrapper
 * Method:    agcAddFarend
 * Signature: ([SI)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_AGCWrapper_agcAddFarend
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     com_example_audiotest_module_AGCWrapper
 * Method:    agcSetAGCConfig
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_AGCWrapper_agcSetAGCConfig
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_example_audiotest_module_AGCWrapper
 * Method:    agcSetProcessSampleTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_AGCWrapper_agcSetProcessSampleTime
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
