/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_audiotest_module_NSWrapper */

#ifndef _Included_com_example_audiotest_module_NSWrapper
#define _Included_com_example_audiotest_module_NSWrapper

#undef com_example_audiotest_module_NSWrapper_NS_MODE_MILD
#define com_example_audiotest_module_NSWrapper_NS_MODE_MILD 0L
#undef com_example_audiotest_module_NSWrapper_NS_MODE_MEDIUM
#define com_example_audiotest_module_NSWrapper_NS_MODE_MEDIUM 1L
#undef com_example_audiotest_module_NSWrapper_NS_MODE_AGGRESSIVE
#define com_example_audiotest_module_NSWrapper_NS_MODE_AGGRESSIVE 2L
/*
 * Class:     com_example_audiotest_module_NSWrapper
 * Method:    nsInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_NSWrapper_nsInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_audiotest_module_NSWrapper
 * Method:    nsDestroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_NSWrapper_nsDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_example_audiotest_module_NSWrapper
 * Method:    nsProcess
 * Signature: ([S[S[S[SI)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_NSWrapper_nsProcess
  (JNIEnv *, jobject, jshortArray, jshortArray, jshortArray, jshortArray, jint);

/*
 * Class:     com_example_audiotest_module_NSWrapper
 * Method:    nsSetPolicy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotest_module_NSWrapper_nsSetPolicy
  (JNIEnv *, jobject, jint);


#endif
